/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Quiz;

import ClasseDados.Conexao;
import static ClasseDados.Conexao.con;
import ClasseDados.usuario;
import com.mysql.jdbc.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Roberto
 */
public class Cadastrar extends javax.swing.JFrame {

    /**
     * Creates new form Cadastrar
     */
    public Cadastrar() {
        initComponents();
        //↓ Add botão no grupo
        btgTipo.add(rdbAdm);
        btgTipo.add(rdbJogador);
        //↓Assim que abre a tela a caixa txtNome ja estara selecionada  
        txtNome.setFocusable(true);
        //↓Assim que abre a tela o RdbAdm já estara selecionado 
        rdbAdm.setSelected(true);
        //↓Coloca o nick do usuario na txtNick
        txtNick.setText(usuario.getNick());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgTipo = new javax.swing.ButtonGroup();
        lblCadastrar = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        lblNick = new javax.swing.JLabel();
        lblSenha = new javax.swing.JLabel();
        lblTipo = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtNickname = new javax.swing.JTextField();
        btnCadastrar = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        rdbJogador = new javax.swing.JRadioButton();
        rdbAdm = new javax.swing.JRadioButton();
        lblCSenha = new javax.swing.JLabel();
        txtNick = new javax.swing.JLabel();
        txtSenha = new javax.swing.JPasswordField();
        txtCSenha = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        lblCadastrar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblCadastrar.setText("Cadastrar");

        lblNome.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblNome.setText("Digite seu nome:");

        lblNick.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblNick.setText("Digite seu nickname:");

        lblSenha.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblSenha.setText("Digite sua senha:");

        lblTipo.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblTipo.setText("Escolha seu tipo:");

        txtNome.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        txtNickname.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        btnCadastrar.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        btnVoltar.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        rdbJogador.setBackground(new java.awt.Color(255, 255, 255));
        rdbJogador.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        rdbJogador.setText("Jogador");

        rdbAdm.setBackground(new java.awt.Color(255, 255, 255));
        rdbAdm.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        rdbAdm.setText("Adm");

        lblCSenha.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblCSenha.setText("Digite a senha novamente:");

        txtNick.setText("Nick");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnVoltar)
                .addGap(112, 112, 112)
                .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(lblTipo)
                        .addGap(14, 14, 14)
                        .addComponent(rdbAdm)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addComponent(rdbJogador))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblNick)
                            .addComponent(lblNome)
                            .addComponent(lblSenha)
                            .addComponent(lblCSenha))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblCadastrar)
                            .addComponent(txtNome, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                            .addComponent(txtNickname)
                            .addComponent(txtSenha)
                            .addComponent(txtCSenha))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addComponent(txtNick)
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCadastrar)
                    .addComponent(txtNick))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNome)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNick)
                    .addComponent(txtNickname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSenha)
                    .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCSenha)
                    .addComponent(txtCSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTipo)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rdbJogador, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(rdbAdm)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(btnVoltar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        //Volta pra tela principal do Adm.
        this.dispose();
        new PrincipalA().setVisible(true);
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        // TODO add your handling code here:
        Conexao dadosBD = new Conexao();
        //↓Declara a variavel de tipo
        int tipo = 0;
        //↓joga tudo o que foi Digitado para dentro de uma variável 
        String Nome = txtNome.getText();
        String Nick = txtNickname.getText();
        String Senha = String.valueOf(txtSenha.getPassword());
        String CSenha = String.valueOf(txtCSenha.getPassword());
        //verifica qual radio button foi selecioando e adiciona um valor à variável tipo
        if(rdbAdm.isSelected() == true){
            tipo = 1;
        }
        if(rdbJogador.isSelected() == true){
            tipo = 2;
        }
        //verifica se a senha e a contra-senha são iguais
        if(Senha.equals(CSenha)){
            dadosBD.getConexao();  
            PreparedStatement st;
            ResultSet rs;
            try {
                //comando para ver se já tem alguém registrado com o mesmo nick
                st = (PreparedStatement) con.prepareStatement("select nickname from usuario where nickname ='"+Nick+"'");
                rs = st.executeQuery();
                if( rs.next()){//←verifica se tem um nick igual no banco
                 JOptionPane.showMessageDialog(null,"Nickname já utilizado");
                 txtNickname.requestFocus();;
                 }else{
                      try {
                        //Query de inserção (as aspas são muito importantes):
                        String sql = "";
                        sql += "INSERT INTO `usuario`(`idusuario`, `nickname`, `nome`, `senha`, `tipo`)";
                        sql += " VALUES ";
                        sql += " (NULL,'"+Nick+ "', '"+Nome+"','"+Senha+"','"+tipo+"')";
                                

                        //Executa
                        PreparedStatement comando = (PreparedStatement) dadosBD.getConexao().prepareStatement(sql);
                        comando.executeUpdate(sql);
                        JOptionPane.showMessageDialog(null,"Cadastrado");
                        this.dispose();
                        new Login().setVisible(true);
                        } catch (Exception e) { //Se deu algum erro...
                            JOptionPane.showMessageDialog(null,e.getMessage());
                            
                        }                        
                    }   
            
               
            } catch (SQLException ex) {
                Logger.getLogger(Cadastrar.class.getName()).log(Level.SEVERE, null, ex);
            }
        //↓se a senha e contra-senha não forem iguais             
        }else{
            JOptionPane.showMessageDialog(null,"As senhas estão diferentes");
            txtSenha.requestFocus();
        }
        dadosBD.FechaConexao();
       
    }//GEN-LAST:event_btnCadastrarActionPerformed
       
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        
        
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new Cadastrar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btgTipo;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel lblCSenha;
    private javax.swing.JLabel lblCadastrar;
    private javax.swing.JLabel lblNick;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JRadioButton rdbAdm;
    private javax.swing.JRadioButton rdbJogador;
    private javax.swing.JPasswordField txtCSenha;
    private javax.swing.JLabel txtNick;
    private javax.swing.JTextField txtNickname;
    private javax.swing.JTextField txtNome;
    private javax.swing.JPasswordField txtSenha;
    // End of variables declaration//GEN-END:variables

}
