/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Quiz;

import ClasseDados.Conexao;
import static ClasseDados.Conexao.con;
import ClasseDados.usuario;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Roberto
 */
public class CriarQuestoes extends javax.swing.JFrame {

    /**
     * Creates new form CriarQuestoes
     */
    public CriarQuestoes() {
        initComponents();
        //↓Assim que abre a tela a caixa txtDQuestao já estara selecionada
        txtDQuestao.setFocusable(true);
        //↓Coloca o nome do usuario na txtNick
        txtNick.setText(usuario.getNick());
        //↓ Add botão no grupo
        btgC.add(rdbC1);
        btgC.add(rdbC2);
        btgC.add(rdbC3);
        btgC.add(rdbC4);
        btgC.add(rdbC5);
        //↓Assim que abre a tela o RdbC1 já estara selecionado
        rdbC1.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        buttonGroup1 = new javax.swing.ButtonGroup();
        btgC = new javax.swing.ButtonGroup();
        lblDQuestao = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDQuestao = new javax.swing.JTextArea();
        lblAlternativa1 = new javax.swing.JLabel();
        txtAlternativa1 = new javax.swing.JTextField();
        lblAlternativa2 = new javax.swing.JLabel();
        txtAlternativa2 = new javax.swing.JTextField();
        lblAlternativa3 = new javax.swing.JLabel();
        txtAlternativa3 = new javax.swing.JTextField();
        lblAlternativa4 = new javax.swing.JLabel();
        btnVoltar = new javax.swing.JButton();
        btnCQuestao = new javax.swing.JButton();
        txtNick = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        rdbC1 = new javax.swing.JRadioButton();
        rdbC2 = new javax.swing.JRadioButton();
        rdbC3 = new javax.swing.JRadioButton();
        txtAlternativa4 = new javax.swing.JTextField();
        rdbC4 = new javax.swing.JRadioButton();
        lblAlternativa5 = new javax.swing.JLabel();
        txtAlternativa5 = new javax.swing.JTextField();
        rdbC5 = new javax.swing.JRadioButton();

        jCheckBox1.setText("jCheckBox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        lblDQuestao.setText("Digite a Questão:");
        lblDQuestao.setToolTipText("");

        txtDQuestao.setColumns(20);
        txtDQuestao.setRows(5);
        jScrollPane1.setViewportView(txtDQuestao);

        lblAlternativa1.setText("Digite a primeira alternativa:");

        lblAlternativa2.setText("Digite a segunda alternativa:");

        lblAlternativa3.setText("Digite a terceira alternativa:");

        lblAlternativa4.setText("Digite a quarta alternativa:");
        lblAlternativa4.setToolTipText("");
        lblAlternativa4.setMaximumSize(new java.awt.Dimension(135, 14));
        lblAlternativa4.setMinimumSize(new java.awt.Dimension(135, 14));
        lblAlternativa4.setPreferredSize(new java.awt.Dimension(135, 14));

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        btnCQuestao.setText("Criar Questão");
        btnCQuestao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCQuestaoActionPerformed(evt);
            }
        });

        txtNick.setText("Nick");

        jLabel1.setText("Marque a correta:");

        lblAlternativa5.setText("Digite a quinta alternativa:");
        lblAlternativa5.setToolTipText("");
        lblAlternativa5.setMaximumSize(new java.awt.Dimension(135, 14));
        lblAlternativa5.setMinimumSize(new java.awt.Dimension(135, 14));
        lblAlternativa5.setPreferredSize(new java.awt.Dimension(135, 14));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtNick))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lblAlternativa3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblAlternativa1)
                                        .addComponent(lblDQuestao))
                                    .addComponent(lblAlternativa2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblAlternativa4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblAlternativa5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtAlternativa4)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtAlternativa1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtAlternativa3, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtAlternativa2, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                                    .addComponent(txtAlternativa5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(rdbC2)
                                            .addComponent(rdbC1)
                                            .addComponent(rdbC3)
                                            .addComponent(rdbC4)
                                            .addComponent(rdbC5))
                                        .addGap(27, 27, 27))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnVoltar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnCQuestao)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtNick)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(lblDQuestao)))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblAlternativa1)
                                .addComponent(txtAlternativa1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(rdbC1))
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblAlternativa2)
                                .addComponent(txtAlternativa2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(rdbC2))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblAlternativa3)
                                .addComponent(txtAlternativa3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(rdbC3))
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAlternativa4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAlternativa4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(rdbC4))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rdbC5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnVoltar)
                            .addComponent(btnCQuestao)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAlternativa5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAlternativa5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        //Volta pra tela principal do Adm.
        this.dispose();
        new PrincipalA().setVisible(true);
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnCQuestaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCQuestaoActionPerformed

        //↓joga tudo o que foi Digitado para dentro de uma variável
        String questao = txtDQuestao.getText();
        String alter1 = txtAlternativa1.getText();
        String alter2 = txtAlternativa2.getText();
        String alter3 = txtAlternativa3.getText();
        String alter4 = txtAlternativa4.getText();
        String alter5 = txtAlternativa5.getText();
        //Declara e inicia variável que vai servir para distiguir cada alternativa correta das não corretas
        int alterp1 = 0;
        int alterp2 = 0;
        int alterp3 = 0;
        int alterp4 = 0;
        int alterp5 = 0; 
        
        //verifica qual radiobutton foi selecionado
        if(rdbC1.isSelected() == true){
            alterp1 = 1;
        }
        if(rdbC2.isSelected() == true){
            alterp2 = 1;
        }
        if(rdbC3.isSelected() == true){
            alterp3 = 1;
        }
         if(rdbC4.isSelected() == true){
            alterp4 = 1;
        }
         if(rdbC5.isSelected() == true){
            alterp5 = 1;
        } 
         
        //verifica se há algum campo em branco 
        if(questao.equals("")){
            JOptionPane.showMessageDialog(null,"Campo Questão em branco");
            txtDQuestao.requestFocus();
        }else if(alter1.equals("")){
           JOptionPane.showMessageDialog(null,"Campo Alternativa 1 em branco");
           txtAlternativa1.requestFocus();
        }else if(alter2.equals("")){
           JOptionPane.showMessageDialog(null,"Campo Alternativa 2 em branco");
           txtAlternativa2.requestFocus();
        }else if(alter3.equals("")){
           JOptionPane.showMessageDialog(null,"Campo Alternativa 3 em branco");
           txtAlternativa3.requestFocus();
        }else if(alter4.equals("")){
           JOptionPane.showMessageDialog(null,"Campo Alternativa 4 em branco");
           txtAlternativa4.requestFocus();
        }else if(alter5.equals("")){
           JOptionPane.showMessageDialog(null,"Campo Alternativa 4 em branco");
           txtAlternativa5.requestFocus();   
        }else{
            Conexao.getConexao();   
            PreparedStatement st;
            ResultSet rs;
            try {
                //verifica se esta questao ja foi criada
                st = (PreparedStatement) con.prepareStatement("select descricao from questoes where descricao ='"+questao+"';");
                rs = st.executeQuery();
                if( rs.next()){//←verifica se tem um nick igual no banco
                    JOptionPane.showMessageDialog(null,"Questão já foi criada");
                    txtDQuestao.requestFocus();
                    
                //verifica se o conteudo inserido em outros campo estão iguais ao conteudo da alternativa 1 
                }else if(alter1.equals(alter2)){
                    JOptionPane.showMessageDialog(null,"Alternativa 1 igual a alternativa 2");
                    txtAlternativa2.requestFocus();
                }else if(alter1.equals(alter3)){
                    JOptionPane.showMessageDialog(null,"Alternativa 1 igual a alternativa 3");
                    txtAlternativa3.requestFocus();
                }else if(alter1.equals(alter4)){
                    JOptionPane.showMessageDialog(null,"Alternativa 1 igual a alternativa 4");
                    txtAlternativa4.requestFocus();
                }else if(alter1.equals(alter5)){
                    JOptionPane.showMessageDialog(null,"Alternativa 1 igual a alternativa 5");
                    txtAlternativa5.requestFocus();
                    
                //verifica se o conteudo inserido em outros campo estão iguais ao conteudo da alternativa 2    
                }else if(alter2.equals(alter3)){
                    JOptionPane.showMessageDialog(null,"Alternativa 2 igual a alternativa 3");
                    txtAlternativa3.requestFocus();
                }else if(alter2.equals(alter4)){
                    JOptionPane.showMessageDialog(null,"Alternativa 2 igual a alternativa 4");
                    txtAlternativa4.requestFocus();
                }else if(alter2.equals(alter5)){
                    JOptionPane.showMessageDialog(null,"Alternativa 2 igual a alternativa 5");
                    txtAlternativa5.requestFocus(); 
                    
                //verifica se o conteudo inserido em outros campo estão iguais ao conteudo da alternativa 3 
                }else if(alter3.equals(alter4)){
                    JOptionPane.showMessageDialog(null,"Alternativa 3 igual a alternativa 4");
                    txtAlternativa4.requestFocus();
                }else if(alter3.equals(alter5)){
                    JOptionPane.showMessageDialog(null,"Alternativa 3 igual a alternativa 5");
                    txtAlternativa5.requestFocus();
                
                //verifica se o conteudo inserido em outros campo estão iguais ao conteudo da alternativa 4    
                 }else if(alter4.equals(alter5)){
                    JOptionPane.showMessageDialog(null,"Alternativa 4 igual a alternativa 5");
                    txtAlternativa5.requestFocus();    
                }else{
                     try {
                        //cria questão
                        String sql = "";
                        sql += "INSERT INTO `questoes`(`idquestoes`, `descricao`)";
                        sql += "VALUES ";
                        sql += "(NULL,'"+questao+"');";
                        //Executa
                        PreparedStatement comando = (PreparedStatement) Conexao.getConexao().prepareStatement(sql);
                        comando.executeUpdate(sql);
                    } catch (Exception e) { //Se deu algum erro...
                        JOptionPane.showMessageDialog(null,e.getMessage());

                    }
                    try {
                    //verifia se a questao foi criada    
                    st = (PreparedStatement) con.prepareStatement("select idquestoes from questoes where descricao ='"+questao+"';");
                    ResultSet rs2;
                    rs2 = st.executeQuery();
                    if( rs2.next()){
                        try {
                        //consulta o id usuario do usuario que esta criando a questão
                            try {     
                                st = (PreparedStatement) con.prepareStatement("select idusuario from usuario where nickname ='"+usuario.getNick()+"';");
                                ResultSet rs3;
                                rs3 = st.executeQuery();
                                if( rs3.next()){
                                        //Inseri as alternativas
                                        String sql = "";
                                        sql += "INSERT INTO `alternativas`(`idalternativa`, `idquestoes`, `idusuario`, `Qdescricao`, `correta`)";
                                        sql += " VALUES ";
                                        sql += " (NULL,'"+rs2.getString("idquestoes")+"','"+rs3.getString("idusuario")+"','"+alter1+"',"+alterp1+"),";
                                        sql += " (NULL,'"+rs2.getString("idquestoes")+"','"+rs3.getString("idusuario")+"','"+alter2+"',"+alterp2+"),";
                                        sql += " (NULL,'"+rs2.getString("idquestoes")+"','"+rs3.getString("idusuario")+"','"+alter3+"',"+alterp3+"),";
                                        sql += " (NULL,'"+rs2.getString("idquestoes")+"','"+rs3.getString("idusuario")+"','"+alter4+"',"+alterp4+"),";
                                        sql += " (NULL,'"+rs2.getString("idquestoes")+"','"+rs3.getString("idusuario")+"','"+alter5+"',"+alterp5+");";
                                        //Executa
                                        PreparedStatement comando = (PreparedStatement) Conexao.getConexao().prepareStatement(sql);
                                        comando.executeUpdate(sql);
                                        JOptionPane.showMessageDialog(null,"Questão criada com sucesso");
                                        //Depois de Criada a questão apaga tudo o que esta dentro do campos  
                                        ApagarTudo();
                                }
                                  
                            }catch (Exception e) { //Se deu algum erro...
                            JOptionPane.showMessageDialog(null,e.getMessage());

                             }
                        }catch (Exception e) { //Se deu algum erro...
                            JOptionPane.showMessageDialog(null,e.getMessage());

                        }
                        
                    }else{
                         JOptionPane.showMessageDialog(null,"Deu tudo ERRADO");
                    }
                    }catch (SQLException ex) {
                    Logger.getLogger(CriarQuestoes.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } 
            }catch (SQLException ex) {
                Logger.getLogger(CriarQuestoes.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        Conexao c = new Conexao();
        c.FechaConexao();
    }//GEN-LAST:event_btnCQuestaoActionPerformed
   
    
    private void ApagarTudo(){
        //Apaga tudo o que esta dentro do campos 
        txtDQuestao.setText("");
        txtAlternativa1.setText("");
        txtAlternativa2.setText("");
        txtAlternativa3.setText("");
        txtAlternativa4.setText("");
        txtAlternativa5.setText("");
        rdbC1.setSelected(true);
    }   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CriarQuestoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CriarQuestoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CriarQuestoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CriarQuestoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CriarQuestoes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btgC;
    private javax.swing.JButton btnCQuestao;
    private javax.swing.JButton btnVoltar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAlternativa1;
    private javax.swing.JLabel lblAlternativa2;
    private javax.swing.JLabel lblAlternativa3;
    private javax.swing.JLabel lblAlternativa4;
    private javax.swing.JLabel lblAlternativa5;
    private javax.swing.JLabel lblDQuestao;
    private javax.swing.JRadioButton rdbC1;
    private javax.swing.JRadioButton rdbC2;
    private javax.swing.JRadioButton rdbC3;
    private javax.swing.JRadioButton rdbC4;
    private javax.swing.JRadioButton rdbC5;
    private javax.swing.JTextField txtAlternativa1;
    private javax.swing.JTextField txtAlternativa2;
    private javax.swing.JTextField txtAlternativa3;
    private javax.swing.JTextField txtAlternativa4;
    private javax.swing.JTextField txtAlternativa5;
    private javax.swing.JTextArea txtDQuestao;
    private javax.swing.JLabel txtNick;
    // End of variables declaration//GEN-END:variables
}
